### ISSUE TITLE
Document secret needs

### ISSUE THREAD

**Issue by ghost** [suda/charts#2]
Install instructions are missing any reference to the secret required to run Ackee. The logical place for this would be in the prerequisites section of the readme, which is currently empty. This will help users more quickly realize chart doesn't ship with a database (ref: suda/charts#1), something that'd be useful to list in the prerequisites section along with the secret.

Example secret:

```
kind: Secret
apiVersion: v1
metadata:
  name: ackee-password
  namespace: ackee
data:
  ACKEE_PASSWORD: ac2zyNAwDag=
type: Opaque
```

May be created with `kubectl create secret`.
